<ul class="breadcrumb">
</ul>
<!-- BEGIN SIDEBAR & CONTENT -->
<div class="row margin-bottom-40">
    <br>
    <center id="cao-anh-phuong">
        <h2>Anh Phương</h2>
        <p>
            <video width="95%" height="100%" controls>
                <source src="<?= $this->basePath() ?>/Anh Phuong.mp4" type="video/mp4">
                <source src="<?= $this->basePath() ?>/Anh Phuong.webm" type="video/webm">
                Your browser does not support HTML5 video. Please upgrade your browser to see the video.
            </video>

        <p>
        <table border=0 cellspacing=5 cellpadding=0>
            <tr><td align=right><b>Resolution:</b></td><td align=left>480p</td></tr>
            <tr><td align=right><b>Video Size:</b></td><td align=left>854 x 480</td></tr>
            <tr><td align=right><b>Display Size:</b></td><td align=left>375 x 667</td></tr>
        </table>


    </center>
</div>
<!-- END SIDEBAR & CONTENT -->